version: '3'

volumes:
  db_data_practice:

services:
  app:
    image: node:14-alpine
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: "development"
      PORT: 5000
      DB_USER: root
      DB_PASS: tiptop123
      DB_NAME: node-express-benchmark
      MYSQL_PORT: 3306
      MYSQL_HOST: mysql
      JWT_SECRET: "AAAAB3NzaC1yc2EAAAADAQABAAABAQCoF"
      MICRO_JWT: |
        -----BEGIN PUBLIC KEY-----
        MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDEO+kKg1jBE3ii3PhgPyxtFDdV
        shG9sQ6UmIlu+BHvyeNkAovtATTOSPI6wnwQj8Ml2/ehvlppgykpDz33eap1kh6I
        gX7zFVOaNdIp01ITxql+wvYL/gyyl6oLmWxOYf/Q7Gl6xQFYAYAB8wMEB7tIbIfp
        06KPaQoNYU/Qov5afwIDAQAB
        -----END PUBLIC KEY-----
    ports:
      - "5000:5000"
    command: "npm run dev"

  mysql:
    image: mysql:5.7.34
    environment:
      MYSQL_ROOT_PASSWORD: tiptop123
      MYSQL_DATABASE: node-express-benchmark
      MYSQL_USER: fieldnation
      MYSQL_PASSWORD: tiptop123
      MYSQL_ROOT_HOST: '%'
    volumes:
      - "db_data_practice:/var/lib/mysql"
    ports:
      - "3306:3306"

